export interface AggregatedStats {
  totalTrades: number;
  wins: number;
  losses: number;
  breakeven: number;
  grossProfit: number;
  grossLoss: number;
  totalPnl: number;
  totalVolume: number;
  winRate: number;
  profitFactor: number;
  avgWin: number;
  avgLoss: number;
  expectancy: number;
  avgRiskReward: number;
  bestTrade: number;
  worstTrade: number;
  avgHoldingTime: number;
  minDuration: number;
  maxDuration: number;
  consecutiveWins: number;
  consecutiveLosses: number;
  maxDrawdown: number;
  sharpeRatio: number;
  durationBuckets: Array<{ range: string; wins: number; losses: number; total: number }>;
  symbolDistribution: Record<string, { count: number; wins: number; pnl: number }>;
  strategyDistribution: Record<string, { count: number; wins: number; pnl: number }>;
  sessionDistribution: Record<string, { count: number; wins: number; pnl: number }>;
  outcomeDistribution: Record<string, number>;
  hourlyStats: Array<{ hour: string; trades: number; wins: number; pnl: number; winRate: number }>;
  dailyWinRate: Array<{ day: string; trades: number; wins: number; pnl: number; winRate: number }>;
  dailyPnl: Array<{ date: string; pnl: number; cumulativePnl: number }>;
  equityCurve?: Array<{ date: string; pnl: number; cumulativePnl: number; symbol: string }>;
  [key: string]: any;
}
